service: docs-website

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ${env:AWS_DEFAULT_REGION, 'us-east-1'}

plugins:
  - serverless-offline

functions:
  index:
    handler: src/functions/index.index
    events:
      - http:
          method: get
          path: /
