name: Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Build and deploy main
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Install API Dependecies
      run: npm i

    - name: serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: deploy
      env:
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    

    # - name: Package for prod
    #   uses: serverless/github-action@master
    #   with:
    #     args: package --stage prod

    # - name: Deploy to prod
    #   uses: serverless/github-action@master
    #   with:
    #     args: deploy --package .serverless --stage prod --force
