name: Run Tests

on:
  pull_request:
    branches:
    - main

jobs:
  buildAndTest:
    name: Test on Pull Request
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - name: Install API Dependencies
      run: npm i

    - name: Check lint
      run: npm run lint

    - name: Tests
      run: npm test